---
title: 10 Big Data Myths
author: Thomas Speidel
date: '2017-08-25'
slug: 10-big-data-myths
categories:
  - critical thinking
  - statistical literacy
tags: []
---

Everyone seems to like top-10 lists and many organizations are interested in Big Data, so it seems timely to write my own top 10 list on Big Data.  A premise is warranted.  Those who know me, know how much I ditest the term "Big Data". Yet, for good or worse, Big Data is here to stay and so it's important that we try clarify what it is and it isn't.

see https://dzone.com/articles/10-big-data-myths-exploded
Gartner: https://www.forbes.com/sites/gartnergroup/2013/03/27/gartners-big-data-definition-consists-of-three-parts-not-to-be-confused-with-three-vs/#30da54dd42f6
Diego slides: https://www.slideshare.net/kuonen/the-power-of-data-insights-big-data-as-the-fuel-and-analytics-as-the-engine-of-the-digital-transformation
https://www.newyorker.com/tech/elements/how-to-call-bullshit-on-big-data-a-practical-guide
https://hbr.org/2016/11/what-artificial-intelligence-can-and-cant-do-right-now

## What is Big Data?
First thing first: definitions. What is Big Data? The hardest thing about Big Data is defining it. Conventionally, Big Data is defined in terms of the 3 or 4 V's:

1.    Volume
2.    Velocity
3.    Variety
4.    Veracity

For an overview of each V, I refer you to Diego Kuonen's excellent [slides] here(https://image.slidesharecdn.com/pdibddsmlmsftfeb12017-170201151005/95/the-power-of-data-insights-big-data-as-the-fuel-and-analytics-as-the-engine-of-the-digital-transformation-9-638.jpg?cb=1485961990).

## Myths & Facts

1. Big Data will enable analytics within the organization.
Not necessarily. You don't need Big Data to become more analytically mature. Many organizations have become analytically astute without Big Data. For instance, look at CERN, Capital One, Wal-Mart, AT&T. As friend Diego Kuonen writes, **Big Data is mostly a data management infrastructure** problem, and less an analytical one.

2. Big Data provides a single source of the truth.
No. As a long time analytics practitioner, I've always struggled with the idea of single source of the truth, which I recognize as being a useful ideal in designing data systems. But when it comes to making sense of data, it is common to have multiple sources of the truth. It all depends on the question one is trying to answer. Consider the trivial reporting of some metric for regulatory compliance vs. reporting for business improvement processes. The two metrics may be given the same name, they may involve the same calculations, but they may come from different systems designed for different purposes.

3. Big Data will make access to data easier
No, or not yet.  

4. Big Data is synonym of HADOOP
Yes. While it is true that there are other standards, tools and technologies, the majority of the Big Data ecosystems are either based on HADOOP or strongly influenced by it. Big Data is becoming a substitute for HADOOP, Apache and any project revolving around them.

5. With Big Data and AI, organizations will no longer need Data Scientists, Data Engineers
No. I'm told similar things were said in the past for coders and the demand has only increased ever since. Data does not automagically analyze itself, no matter how much AI you inject. Let's not confuse automatable tasks with the myth of self-learning, eloquently summarized by [Andrew Ng](https://hbr.org/2016/11/what-artificial-intelligence-can-and-cant-do-right-now): *If a typical person can do a mental task with less than one second of thought, we can probably automate it using AI either now or in the near future.*

With more data the task of organizing, curating, identifying, and preparing the data for analysis can only increase.

6. Users will be able to interact with Big Data more easily
I have no evidence of this, but I speculate that accessing data will be harder.

7. The More the Data, the Better
False. Maybe that's true for the NSA (though even for them, I have some doubts). But most organizations do not have the deep pockets of a secretive government organization. Predictive models are usually built on samples: seldom is the whole data ever needed. There are also problems with having too large of a dataset, that to this day, we have not quite solved yet. Curse of large numbers.

8. Open Source is key for Big Data
True. When one looks at the building blocks of most Big Data technology, they will soon realize it's an ocean of open source initiatives without which we probably would not be having this conversation.